@startuml state

(*) --> [ User create CR ] "Created"

"Created" --> "Configuring"
"Created" --> [ Port have been used ] "Deleted"
"Created" --> "Created"

"Configuring" --> "Configuring"
"Configuring" --> "Configured"

"Configured" --> [ Configuration have been updated ] "Configuring"
"Configured" --> [ User remove CR ] "Deleting"

"Deleting" --> "Deleting"
"Deleting" --> "Deleted"

"Deleted" --> [ CR have been removed ] (*)

@enduml
